RentalService.Web/Controllers/CityController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Mapster;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RentalService.BL.Contracts;
using RentalService.BL.DTO;
using RentalService.Web.ViewModels;

namespace RentalService.Web.Controllers
{
    public class CityController : Controller
    {
        private readonly ICityService cityService;
        private readonly ICountryService countryService;

        public CityController(ICityService cityService, ICountryService countryService)
        {
            this.cityService = cityService;
            this.countryService = countryService;
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index()
        {
            var cities = await cityService.GetAllCitiesAsync();

            return View(cities?.Adapt<IEnumerable<CityVM>>());
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return BadRequest("City ID wasn't set");
            }

            try
            {
                var city = await cityService.GetCityAsync(id);

                return View(city.Adapt<CityVM>());
            }
            catch
            {
                return NotFound();
            }
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create(int? countryId, string countryName)
        {
            if (countryId == null)
            {
                var countries = await countryService.GetAllCountriesAsync();
                ViewData["Countries"] = new SelectList(countries, "Id", "Name");
            }
            else
            {
                ViewData["CountryId"] = countryId;
                ViewData["CountryName"] = countryName;
            }

            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create([Bind("Name, CountryId")] CityVM city)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await cityService.UpdateCityAsync(city.Adapt<CityDTO>());
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CityExists(city.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                return RedirectToAction(nameof(Index));
            }

            var countries = await countryService.GetAllCountriesAsync();
            ViewData["Countries"] = new SelectList(countries, "Id", "Name");

            return View(city);
        }

        [HttpGet]
        [Authorize]
        public ActionResult AutocompleteSearch(string term, string countryName)
        {
            var cities = cityService.FindCitiesAsync(term, countryName)
                .GetAwaiter()
                .GetResult()
                .Select(c => new { value = c.Name });

            return Json(cities);
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return BadRequest("City ID wasn't set");
            }

            try
            {
                var city = await cityService.GetCityAsync(id);

                var countries = await countryService.GetAllCountriesAsync();
                ViewData["Countries"] = new SelectList(countries, "Id", "Name");

                return View(city.Adapt<CityVM>());
            }
            catch
            {
                return NotFound();
            }
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit([Bind("Id, Name, CountryId")] CityVM city)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await cityService.UpdateCityAsync(city.Adapt<CityDTO>());
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CityExists(city.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                return RedirectToAction(nameof(Index));
            }

            var countries = await countryService.GetAllCountriesAsync();
            ViewData["Countries"] = new SelectList(countries, "Id", "Name");

            return View(city);
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return BadRequest("City ID wasn't set");
            }

            try
            {
                var city = await cityService.GetCityAsync(id);

                return View(city.Adapt<CityVM>());
            }
            catch
            {
                return NotFound();
            }
        }

        [HttpPost, ActionName("Delete")]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await cityService.DeleteCityAsync(id);

            return RedirectToAction(nameof(Index));
        }

        private bool CityExists(int id)
        {
            return cityService.CityExists(id);
        }
    }
}

RentalService.Web/Controllers/CountryController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Mapster;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RentalService.BL.Contracts;
using RentalService.BL.DTO;
using RentalService.Web.ViewModels;

namespace RentalService.Web.Controllers
{
    public class CountryController : Controller
    {
        private readonly ICountryService service;

        public CountryController(ICountryService countryService)
        {
            service = countryService;
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index()
        {
            var countries = await service.GetAllCountriesAsync();

            return View(countries?.Adapt<IEnumerable<CountryVM>>());
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return BadRequest("Country ID wasn't set");
            }

            try
            {
                var country = await service.GetCountryAsync(id);

                return View(country.Adapt<CountryVM>());
            }
            catch
            {
                return NotFound();
            }
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create([Bind("Name, Code")] CountryVM country)
        {
            if (ModelState.IsValid)
            {
                await service.AddCountryAsync(country.Adapt<CountryDTO>());

                return RedirectToAction(nameof(Index));
            }

            return View(country);
        }

        [HttpGet]
        [Authorize]
        public ActionResult AutocompleteSearch(string term)
        {
            var countries = service.FindCountriesAsync(term)
                .GetAwaiter()
                .GetResult()
                .Select(c => new { value = c.Name });

            return Json(countries);
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return BadRequest("Country ID wasn't set");
            }

            try
            {
                var country = await service.GetCountryAsync(id);

                return View(country.Adapt<CountryVM>());
            }
            catch
            {
                return NotFound();
            }
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit([Bind("Id, Name, Code")] CountryVM country)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await service.UpdateCountryAsync(country.Adapt<CountryDTO>());
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CountryExists(country.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                return RedirectToAction(nameof(Index));
            }

            return View(country);
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return BadRequest("Country ID wasn't set");
            }

            try
            {
                var country = await service.GetCountryAsync(id);

                return View(country.Adapt<CountryVM>());
            }
            catch
            {
                return NotFound();
            }
        }

        [HttpPost, ActionName("Delete")]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await service.DeleteCountryAsync(id);

            return RedirectToAction(nameof(Index));
        }

        private bool CountryExists(int id)
        {
            return service.CountryExists(id);
        }
    }
}

RentalService.Web/Views/City/Create.cshtml
@model CityVM

@{
    ViewData["Title"] = "Create";
}

<h1>Create city</h1>
<hr />

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" autocomplete="off" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="CountryName" class="control-label"></label>
                @if (ViewBag.CountryId != null)
                {
                    <input asp-for="CountryId" class="form-control" hidden value="@ViewBag.CountryId" />
                    <input asp-for="CountryName" class="form-control" disabled value="@ViewBag.CountryName" />
                }
                else
                {
                    <select asp-for="CountryId" class="form-control" asp-items="ViewBag.Countries" />
                }
                <br />
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    @if (ViewBag.CountryId != null)
    {
        <a asp-controller="Country" asp-action="Edit" asp-route-id="@ViewBag.CountryId">Back to Country</a>
    }
    else
    {
        <a asp-action="Index">Go to Cities</a>
    }
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RentalService.Web/Views/City/Delete.cshtml
@model CityVM

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete city</h1>

<h3>Are you sure you want to delete this?</h3>
<hr />

<div>
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CountryName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CountryName)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Go to Cities</a>
    </form>
</div>

RentalService.Web/Views/City/Details.cshtml
@model CityVM

@{
    ViewData["Title"] = "Details";
}

<h1>Details about city</h1>
<hr />

<div>
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CountryName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CountryName)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Go to Cities</a>
</div>

RentalService.Web/Views/City/Edit.cshtml
@model CityVM

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit city</h1>
<hr />

<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CountryName" class="control-label"></label>
                <select asp-for="CountryId" class="form-control" asp-items="ViewBag.Countries"></select>
                <span asp-validation-for="CountryId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Go to Cities</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RentalService.Web/Views/City/Index.cshtml
@model IEnumerable<CityVM>

@{
    ViewData["Title"] = "Index";
}

<h1>Cities</h1>

<p>
    <a asp-action="Create">Create new</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CountryName)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model) {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CountryName)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>