RentalService.Web/Controllers/RentalCompanyController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Mapster;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RentalService.BL.Contracts;
using RentalService.BL.DTO;
using RentalService.Web.ViewModels;

namespace RentalService.Web.Controllers
{
    public class RentalCompanyController : Controller
    {
        private readonly IRentalCompanyService service;

        public RentalCompanyController(IRentalCompanyService rentalCompanyService)
        {
            service = rentalCompanyService;
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index()
        {
            var countries = await service.GetAllRentalCompaniesAsync();

            return View(countries?.Adapt<IEnumerable<RentalCompanyVM>>());
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return BadRequest("Rental company ID wasn't set");
            }

            try
            {
                var rentalCompany = await service.GetRentalCompanyAsync(id);

                return View(rentalCompany.Adapt<RentalCompanyVM>());
            }
            catch
            {
                return NotFound();
            }
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }

        [HttpGet]
        [Authorize]
        public ActionResult AutocompleteSearch(string term, string cityName)
        {
            var companies = service.FindRentalCompaniesAsync(term, cityName)
                .GetAwaiter()
                .GetResult()
                .Select(c => new { value = c.Name });

            return Json(companies);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create(RentalCompanyVM rentalCompany)
        {
            if (ModelState.IsValid)
            {
                await service.AddRentalCompanyAsync(rentalCompany.Adapt<RentalCompanyDTO>());

                return RedirectToAction(nameof(Index));
            }

            return View(rentalCompany);
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return BadRequest("Rental company ID wasn't set");
            }

            try
            {
                var rentalCompany = await service.GetRentalCompanyAsync(id);

                return View(rentalCompany.Adapt<RentalCompanyVM>());
            }
            catch
            {
                return NotFound();
            }
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(RentalCompanyVM rentalCompany)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await service.UpdateRentalCompanyAsync(rentalCompany.Adapt<RentalCompanyDTO>());
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RentalCompanyExists(rentalCompany.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                return RedirectToAction(nameof(Index));
            }

            return View(rentalCompany);
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return BadRequest("Rental company ID wasn't set");
            }

            try
            {
                var rentalCompany = await service.GetRentalCompanyAsync(id);

                return View(rentalCompany.Adapt<RentalCompanyVM>());
            }
            catch
            {
                return NotFound();
            }
        }

        [HttpPost, ActionName("Delete")]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await service.DeleteRentalCompanyAsync(id);

            return RedirectToAction(nameof(Index));
        }

        private bool RentalCompanyExists(int id)
        {
            return service.RentalCompanyExists(id);
        }
    }
}

RentalService.Web/Controllers/RentalPointController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using Mapster;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RentalService.BL.Contracts;
using RentalService.BL.DTO;
using RentalService.Web.ViewModels;

namespace RentalService.Web.Controllers
{
    [Authorize(Roles = "Admin")]
    public class RentalPointController : Controller
    {
        private readonly IRentalPointService rentalPointService;
        private readonly IRentalCompanyService companyService;
        private readonly ICityService cityService;

        public RentalPointController(IRentalPointService rentalPointService, IRentalCompanyService companyService, ICityService cityService)
        {
            this.rentalPointService = rentalPointService;
            this.companyService = companyService;
            this.cityService = cityService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var rentalPoints = await rentalPointService.GetAllRentalPointsAsync();

            return View(rentalPoints?.Adapt<IEnumerable<RentalPointVM>>());
        }

        [HttpGet]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return BadRequest("Rental point ID wasn't set");
            }

            try
            {
                var rentalPoint = await rentalPointService.GetRentalPointAsync(id);

                return View(rentalPoint.Adapt<RentalPointVM>());
            }
            catch
            {
                return NotFound();
            }
        }

        [HttpGet]
        public async Task<IActionResult> Create(int? companyId, string companyName)
        {
            if (companyId == null)
            {
                var companies = await companyService.GetAllRentalCompaniesAsync();
                ViewData["Companies"] = new SelectList(companies, "Id", "Name");
            }
            else
            {
                ViewData["CompanyId"] = companyId;
                ViewData["CompanyName"] = companyName;
            }

            var cities = await cityService.GetAllCitiesAsync();
            ViewData["Cities"] = new SelectList(cities, "Id", "Name");

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(RentalPointVM rentalPoint)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await rentalPointService.UpdateRentalPointAsync(rentalPoint.Adapt<RentalPointDTO>());
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RentalPointExists(rentalPoint.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                return RedirectToAction(nameof(Index));
            }

            var companies = await companyService.GetAllRentalCompaniesAsync();
            ViewData["Companies"] = new SelectList(companies, "Id", "Name");

            var cities = await cityService.GetAllCitiesAsync();
            ViewData["Cities"] = new SelectList(cities, "Id", "Name");

            return View(rentalPoint);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return BadRequest("Rental point ID wasn't set");
            }

            try
            {
                var rentalPoint = await rentalPointService.GetRentalPointAsync(id);

                var companies = await companyService.GetAllRentalCompaniesAsync();
                ViewData["Companies"] = new SelectList(companies, "Id", "Name");

                var cities = await cityService.GetAllCitiesAsync();
                ViewData["Cities"] = new SelectList(cities, "Id", "Name");

                return View(rentalPoint.Adapt<RentalPointVM>());
            }
            catch
            {
                return NotFound();
            }
        }

        [HttpPost]
        public async Task<IActionResult> Edit(RentalPointVM rentalPoint)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await rentalPointService.UpdateRentalPointAsync(rentalPoint.Adapt<RentalPointDTO>());
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RentalPointExists(rentalPoint.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                return RedirectToAction(nameof(Index));
            }

            var companies = await companyService.GetAllRentalCompaniesAsync();
            ViewData["Companies"] = new SelectList(companies, "Id", "Name");

            var cities = await cityService.GetAllCitiesAsync();
            ViewData["Cities"] = new SelectList(cities, "Id", "Name");

            return View(rentalPoint);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return BadRequest("Rental point ID wasn't set");
            }

            try
            {
                var rentalPoint = await rentalPointService.GetRentalPointAsync(id);

                return View(rentalPoint.Adapt<RentalPointVM>());
            }
            catch
            {
                return NotFound();
            }
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await rentalPointService.DeleteRentalPointAsync(id);

            return RedirectToAction(nameof(Index));
        }

        private bool RentalPointExists(int id)
        {
            return rentalPointService.RentalPointExists(id);
        }
    }
}

RentalService.Web/Views/RentalPoint/Create.cshtml
@model RentalPointVM

@{
    ViewData["Title"] = "Create";
}

<h1>Create rental point</h1>
<hr />

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <select asp-for="CityId" class="form-control" asp-items="ViewBag.Cities"></select>
            </div>

            <div class="form-group">
                <label asp-for="CompanyName" class="control-label"></label>
                @if (ViewBag.CompanyId != null)
                {
                    <input asp-for="CompanyId" class="form-control" hidden value="@ViewBag.CompanyId" />
                    <input asp-for="CompanyName" class="form-control" disabled value="@ViewBag.CompanyName" />
                }
                else
                {
                    <select asp-for="CompanyId" class="form-control" asp-items="ViewBag.Companies"></select>
                }
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    @if (ViewBag.CompanyId != null)
    {
        <a asp-controller="RentalCompany" asp-action="Edit" asp-route-id="@ViewBag.CompanyId">Back to Rental company</a>
    }
    else
    {
        <a asp-action="Index">Go to Rental points</a>
    }
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RentalService.Web/Views/RentalPoint/Delete.cshtml
@model RentalPointVM

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete rental point</h1>

<h3>Are you sure you want to delete this?</h3>
<hr />

<div>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.City)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.City.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CompanyName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CompanyName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.RentalPointCars)
        </dt>
    </dl>

    <table class="table">
        <thead>
            <tr>
                <th>Car</th>
                <th>Address</th>
                <th>Cost</th>
                <th>Count</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (RentalPointCarVM rentalPointCar in Model.RentalPointCars)
            {
                <tr id="row_@rentalPointCar.Id">
                    <td>@rentalPointCar.CarName</td>
                    <td>@rentalPointCar.RentalPoint.Address</td>
                    <td>@rentalPointCar.Cost</td>
                    <td>@rentalPointCar.Count</td>
                </tr>
            }
        </tbody>
    </table>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Go to Rental points</a>
    </form>
</div>

RentalService.Web/Views/RentalPoint/Details.cshtml
@model RentalPointVM

@{
    ViewData["Title"] = "Details";
}

<h1>Details about rental point</h1>
<hr />

<div>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.City)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.City.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CompanyName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CompanyName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.RentalPointCars)
        </dt>
    </dl>
</div>

<table class="table">
    <thead>
        <tr>
            <th>Car</th>
            <th>Address</th>
            <th>Cost</th>
            <th>Count</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (RentalPointCarVM rentalPointCar in Model.RentalPointCars)
        {
            <tr id="row_@rentalPointCar.Id">
                <td>@rentalPointCar.CarName</td>
                <td>@rentalPointCar.RentalPoint.Address</td>
                <td>@rentalPointCar.Cost</td>
                <td>@rentalPointCar.Count</td>
            </tr>
        }
    </tbody>
</table>

<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Go to Rental points</a>
</div>

RentalService.Web/Views/RentalPoint/Edit.cshtml
@model RentalPointVM

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit rental point</h1>
<hr />

<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <select asp-for="CityId" class="form-control" asp-items="ViewBag.Cities"></select>
                <span asp-validation-for="CityId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CompanyName" class="control-label"></label>
                <select asp-for="CompanyId" class="form-control" asp-items="ViewBag.Companies"></select>
                <span asp-validation-for="CompanyId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
            <div>
                <a asp-action="Index">Go to Rental points</a>
            </div>
        </form>
    </div>
</div>
<br />
<hr />

<h4>Cars</h4>
<p>
    @Html.ActionLink("Create new", "Create", "RentalPointCar", new { pointId = Model.Id })
</p>
<table class="table">
    <thead>
        <tr>
            <th>Car</th>
            <th>Address</th>
            <th>Cost</th>
            <th>Count</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (RentalPointCarVM rentalPointCar in Model.RentalPointCars)
        {
            <tr id="row_@rentalPointCar.Id">
                <td>@rentalPointCar.CarName</td>
                <td>@rentalPointCar.RentalPoint.Address</td>
                <td>@rentalPointCar.Cost</td>
                <td>@rentalPointCar.Count</td>
                <td>
                    <a asp-controller="RentalPointCar" asp-action="Edit" asp-route-id="@rentalPointCar.Id" class="btn btn-outline-dark">Edit</a>
                    <a asp-controller="RentalPointCar" asp-action="Details" asp-route-id="@rentalPointCar.Id" class="btn btn-outline-dark">Details</a>
                    <a href="#" class="btn btn-danger" onclick="confirmDelete(@rentalPointCar.Id)">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

<div class="modal fade" id="deleteDialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title">Delete car</h3>
            </div>
            <div class="modal-body">
                <h4>Are you sure you want to delete this?</h4>
            </div>
            <div class="modal-footer">
                <a href="#" class="btn btn-default" data-dismiss="modal">Cancel</a>
                <a href="#" class="btn btn-success" onclick="deleteCar()">Confirm</a>
            </div>
        </div>
    </div>
</div>

<input type="hidden" id="carId" />

<script>
    var confirmDelete = function (carId) {
        $("#carId").val(carId);
        $("#deleteDialog").modal('show');
    }

    var deleteCar = function () {
        var carId = $("#carId").val();

        $.ajax({
            type: "POST",
            url: "/RentalPointCar/Delete",
            data: { id: carId },
            success: function () {
                $("#deleteDialog").modal("hide");
                $("#row_" + carId).remove();

            }
        })
    }
</script>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RentalService.Web/Views/RentalPoint/Index.cshtml
@model IEnumerable<RentalPointVM>

@{
    ViewData["Title"] = "Index";
}

<h1>Rental points</h1>

<p>
    <a asp-action="Create">Create new</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.City)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CompanyName)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model) {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Address)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.City.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CompanyName)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>