RentalService.Web/Controllers/BrandController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using Mapster;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RentalService.BL.Contracts;
using RentalService.BL.DTO;
using RentalService.Web.ViewModels;

namespace RentalService.Web.Controllers
{
    [Authorize(Roles = "Admin")]
    public class BrandController : Controller
    {
        private readonly IBrandService service;

        public BrandController(IBrandService brandService)
        {
            service = brandService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var brands = await service.GetAllBrandsAsync();

            return View(brands?.Adapt<IEnumerable<BrandVM>>());
        }

        [HttpGet]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return BadRequest("Brand ID wasn't set");
            }

            try
            {
                var brand = await service.GetBrandAsync(id);

                return View(brand.Adapt<BrandVM>());
            }
            catch
            {
                return NotFound();
            }
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("Name")] BrandVM brand)
        {
            if (ModelState.IsValid)
            {
                await service.AddBrandAsync(brand.Adapt<BrandDTO>());

                return RedirectToAction(nameof(Index));
            }

            return View(brand);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return BadRequest("Brand ID wasn't set");
            }

            try
            {
                var brand = await service.GetBrandAsync(id);

                return View(brand.Adapt<BrandVM>());
            }
            catch
            {
                return NotFound();
            }
        }

        [HttpPost]
        public async Task<IActionResult> Edit([Bind("Id, Name")] BrandVM brand)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await service.UpdateBrandAsync(brand.Adapt<BrandDTO>());
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BrandExists(brand.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                return RedirectToAction(nameof(Index));
            }

            return View(brand);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return BadRequest("Brand ID wasn't set");
            }

            try
            {
                var brand = await service.GetBrandAsync(id);

                return View(brand.Adapt<BrandVM>());
            }
            catch
            {
                return NotFound();
            }
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await service.DeleteBrandAsync(id);

            return RedirectToAction(nameof(Index));
        }

        private bool BrandExists(int id)
        {
            return service.BrandExists(id);
        }
    }
}

RentalService.Web/Controllers/CarController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using Mapster;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RentalService.BL.Contracts;
using RentalService.BL.DTO;
using RentalService.Web.ViewModels;

namespace RentalService.Web.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CarController : Controller
    {
        private readonly ICarService carService;
        private readonly IBrandService brandService;

        public CarController(ICarService carService, IBrandService brandService)
        {
            this.carService = carService;
            this.brandService = brandService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var cars = await carService.GetAllCarsAsync();

            return View(cars?.Adapt<IEnumerable<CarVM>>());
        }

        [HttpGet]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return BadRequest("Car ID wasn't set");
            }

            try
            {
                var car = await carService.GetCarAsync(id);

                return View(car.Adapt<CarVM>());
            }
            catch
            {
                return NotFound();
            }
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var brands = await brandService.GetAllBrandsAsync();
            ViewData["Brands"] = new SelectList(brands, "Id", "Name");

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("Name, SeatCount, FuelConsumption, BrandId")] CarVM car)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await carService.UpdateCarAsync(car.Adapt<CarDTO>());
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CarExists(car.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                return RedirectToAction(nameof(Index));
            }

            var brands = await brandService.GetAllBrandsAsync();
            ViewData["Brands"] = new SelectList(brands, "Id", "Name");

            return View(brands);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return BadRequest("Car ID wasn't set");
            }

            try
            {
                var car = await carService.GetCarAsync(id);

                var brands = await brandService.GetAllBrandsAsync();
                ViewData["Brands"] = new SelectList(brands, "Id", "Name");

                return View(car.Adapt<CarVM>());
            }
            catch
            {
                return NotFound();
            }
        }

        [HttpPost]
        public async Task<IActionResult> Edit(CarVM car)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await carService.UpdateCarAsync(car.Adapt<CarDTO>());
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CarExists(car.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                return RedirectToAction(nameof(Index));
            }

            var brands = await brandService.GetAllBrandsAsync();
            ViewData["Brands"] = new SelectList(brands, "Id", "Name");

            return View(car);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return BadRequest("Car ID wasn't set");
            }

            try
            {
                var car = await carService.GetCarAsync(id);

                return View(car.Adapt<CarVM>());
            }
            catch
            {
                return NotFound();
            }
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await carService.DeleteCarAsync(id);

            return RedirectToAction(nameof(Index));
        }

        private bool CarExists(int id)
        {
            return carService.CarExists(id);
        }
    }
}

RentalService.Web/Controllers/CityController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Mapster;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RentalService.BL.Contracts;
using RentalService.BL.DTO;
using RentalService.Web.ViewModels;

namespace RentalService.Web.Controllers
{
    public class CityController : Controller
    {
        private readonly ICityService cityService;
        private readonly ICountryService countryService;

        public CityController(ICityService cityService, ICountryService countryService)
        {
            this.cityService = cityService;
            this.countryService = countryService;
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index()
        {
            var cities = await cityService.GetAllCitiesAsync();

            return View(cities?.Adapt<IEnumerable<CityVM>>());
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return BadRequest("City ID wasn't set");
            }

            try
            {
                var city = await cityService.GetCityAsync(id);

                return View(city.Adapt<CityVM>());
            }
            catch
            {
                return NotFound();
            }
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create(int? countryId, string countryName)
        {
            if (countryId == null)
            {
                var countries = await countryService.GetAllCountriesAsync();
                ViewData["Countries"] = new SelectList(countries, "Id", "Name");
            }
            else
            {
                ViewData["CountryId"] = countryId;
                ViewData["CountryName"] = countryName;
            }

            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create([Bind("Name, CountryId")] CityVM city)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await cityService.UpdateCityAsync(city.Adapt<CityDTO>());
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CityExists(city.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                return RedirectToAction(nameof(Index));
            }

            var countries = await countryService.GetAllCountriesAsync();
            ViewData["Countries"] = new SelectList(countries, "Id", "Name");

            return View(city);
        }

        [HttpGet]
        [Authorize]
        public ActionResult AutocompleteSearch(string term, string countryName)
        {
            var cities = cityService.FindCitiesAsync(term, countryName)
                .GetAwaiter()
                .GetResult()
                .Select(c => new { value = c.Name });

            return Json(cities);
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return BadRequest("City ID wasn't set");
            }

            try
            {
                var city = await cityService.GetCityAsync(id);

                var countries = await countryService.GetAllCountriesAsync();
                ViewData["Countries"] = new SelectList(countries, "Id", "Name");

                return View(city.Adapt<CityVM>());
            }
            catch
            {
                return NotFound();
            }
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit([Bind("Id, Name, CountryId")] CityVM city)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await cityService.UpdateCityAsync(city.Adapt<CityDTO>());
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CityExists(city.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                return RedirectToAction(nameof(Index));
            }

            var countries = await countryService.GetAllCountriesAsync();
            ViewData["Countries"] = new SelectList(countries, "Id", "Name");

            return View(city);
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return BadRequest("City ID wasn't set");
            }

            try
            {
                var city = await cityService.GetCityAsync(id);

                return View(city.Adapt<CityVM>());
            }
            catch
            {
                return NotFound();
            }
        }

        [HttpPost, ActionName("Delete")]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await cityService.DeleteCityAsync(id);

            return RedirectToAction(nameof(Index));
        }

        private bool CityExists(int id)
        {
            return cityService.CityExists(id);
        }
    }
}

RentalService.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/lib/jquery-ui/jquery-ui.css" />

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-ui/jquery-ui.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
</head>
<body>
    <div class="container-fluid">
        <div class="row min-vh-100">
            <nav class="col-2 collapse d-md-flex bg-dark text-light pt-2" id="sidebar">
                <ul class="nav flex-column">
                    <li class="nav-item">
                        <a class="nav-link navbar-brand">Service Rental</a>
                    </li>

                    @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                    {
                        <li class="nav-item">
                            <a class="nav-link">Administration</a>
                            <ul class="nav flex-column ml-3">
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="Brand" asp-action="Index">Brands</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="Car" asp-action="Index">Cars</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="City" asp-action="Index">Cities</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="Country" asp-action="Index">Countries</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="RentalCompany" asp-action="Index">Rental companies</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="RentalPoint" asp-action="Index">Rental points</a>
                                </li>
                            </ul>
                        </li>
                    }

                    @if (User.Identity.IsAuthenticated)
                    {
                        <li class="nav-item">
                            <a class="nav-link">Rent</a>
                            <ul class="nav flex-column ml-3">
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="RentalPointCar" asp-action="Index">Cars</a>
                                </li>
                            </ul>
                        </li>

                        <li class="nav-item">
                            <br />
                            <a href="#" class="nav-link" data-toggle="modal" data-target=".logout-modal">Logout</a>
                        </li>
                    }
                </ul>
            </nav>

            <div class="col pt-2">
                @RenderBody()
            </div>
        </div>
    </div>

    <div class="modal logout-modal" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog modal-sm">
            <div class="modal-content">
                <div class="modal-header"><h4>Logout<i class="fa fa-lock"></i></h4></div>
                <div class="modal-body"><i class="fa fa-question-circle"></i> Are you sure you want to log-off?</div>
                <div class="modal-footer"><a asp-controller="Account" asp-action="Logout" class="btn btn-success btn-block">Logout</a></div>
            </div>
        </div>
    </div>

    @RenderSection("Scripts", required: false)
</body>
</html>